### ISSUE TITLE
リソース設計

### ISSUE THREAD

**Issue by yocajii** [yocajii/hamattimer#18]

**Comment by yocajii** [comment]
| Method | Path | Description |
|-|-|-|
| GET | / | サービス説明画面を表示する |
| GET | /editor | 記録画面を表示する |

記録画面は `editor` より適切な単語が無いか、悩んでいます。

## 参考資料

### サービス説明画面

![Image](https://user-images.githubusercontent.com/33394676/187357236-2f29fffe-f715-4e85-b89d-8163397c9538.png)

### 記録画面

![Image](https://user-images.githubusercontent.com/33394676/187357247-4a14842c-a5d5-409e-af85-958f48613ff9.png)

**Comment by yoshitsugu** [comment]
- 「解決したいこと」ごとにURLを与えたりはしなくていいでしょうか？
- > 記録画面は editor より適切な単語が無いか、悩んでいます。
  - タイマー画面なので `timer` とかですかね〜
  - editorでも大丈夫だとは思います〜

**Comment by yocajii** [comment]
> 「解決したいこと」ごとにURLを与えたりはしなくていいでしょうか？

今のところ、取れる記録は1件だけ（履歴を持たない）という形で考えています。
プロトタイプを使ってみてやっぱり履歴も必要となった時は、示してくださったように「解決したいこと」ごとにURLを持つようにすると良さそうですね 👀📝 

> タイマー画面なので `timer` とかですかね〜

たしかに違和感ないです！ `/timer` にしようと思います。
| Method | Path | Description |
|-|-|-|
| GET | / | サービス説明画面を表示する |
| GET | /timer | 記録画面を表示する |

**Comment by yocajii** [comment]
リソース・DB設計のプラクティスは修了となったためクローズ。
