### ISSUE TITLE
文字列入力でMarkdownのプレビューのレイアウトが崩れる

### ISSUE THREAD

**Issue by mh-mobile** [yocajii/hamattimer#232]
# 概要

長いアスキー文字列を入力すると、Markdownのプレビューの文字列が画面から
はみ出るレイアウト崩れが発生します。

例えば、Googleの検索文字列のような長いURLを貼るケースでは、この事象に遭遇する可能性があります。

# 発生箇所

解決したいことや試したことの入力欄で発生します。

# スクリーンショット

### アスキー文字列のみを入力した場合

下部のボタンも横にずれて画面からはみ出ます。

![ng](https://user-images.githubusercontent.com/13811034/204066600-5447d483-498c-4d57-88cd-6457d7eea964.gif)

はまったいまーの[Google検索結果のURL](https://www.google.com/search?q=%E3%81%AF%E3%81%BE%E3%81%A3%E3%81%9F%E3%81%84%E3%81%BE%E3%83%BC&sxsrf=ALiCzsa1cuTnOrjSQCTEDSG1FU6kUpUW2g%3A1669424129384&ei=AWSBY5jsFpaZseMP6fm5mAY&ved=0ahUKEwjY8NfB0cr7AhWWTGwGHel8DmMQ4dUDCA8&uact=5&oq=%E3%81%AF%E3%81%BE%E3%81%A3%E3%81%9F%E3%81%84%E3%81%BE%E3%83%BC&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIHCAAQHhCiBDIFCAAQogQyBQgAEKIEMgUIABCiBDoECCMQJzoGCAAQBBADOg0IABAEEIAEELEDEIMBOg0IABAEEIAEELEDELEDOgcIABAEEIAEOgoIABAEEIAEELEDOgoIABCxAxCxAxBDOgQIABBDOgUIABCABEoECEEYAEoECEYYAFAAWKgMYJoRaABwAXgAgAHFAYgB7AySAQQwLjExmAEAoAEBwAEB&sclient=gws-wiz-serp)を貼り付けた場合は、以下になります。

![ng2](https://user-images.githubusercontent.com/13811034/204067014-a88d02ce-0e84-4588-b668-5acb925f06f0.gif)

### アスキー文字列 + 空白を入力した場合 (OKパターン)

![ok1](https://user-images.githubusercontent.com/13811034/204066624-4803d719-7d20-4590-8caf-db1cc9923614.gif)

### マルチバイト文字列を入力した場合 (OKパターン)

![ok2](https://user-images.githubusercontent.com/13811034/204066625-87457ffe-c301-40fc-8e37-c712a32d47e2.gif)

**Comment by yocajii** [comment]
#233 にて対応済み
