### ISSUE TITLE
DB（localStorage）設計

### ISSUE THREAD

**Issue by yocajii** [yocajii/hamattimer#44]
DBを使用しないため、代わりにlocalStorageに格納するデータ構造を検討します。
レビューしていただいたり実装してみたりする中で、Reactで扱いやすい構造が分かったら、より良い構造に合わせていきたいと考えています。

- Key
  `problem`
- Value
  ```
  {
    tobe: "期待する結果",
    asis: "実際の結果",
    log: "エラーメッセージ、ログ",
    limit: "タイマーの設定時間",
    started_at: "スタートボタンを押した時間"
  }
  ```

- Key
  `trials`
- Value
  ```
  {
    [
      id: "連番",
      guess: "考えたこと・調べたこと",
      operation: "やったこと",
      result: "やったことの結果"
    ]
  }
  ```

**Comment by yoshitsugu** [comment]
- logだと `console.log` みたいにログ出力っぽく見えるので、 `log_message` とかのほうがいいかもしれません。もしくは解決したい課題、と捉えて、 issueとかproblemとかでもいいかもしれません。
- `limit` はタイマーのカウントダウン開始時間ですよね。うっかりタブを閉じてしまったらまた開いたときに `limit` からカウントダウン開始される感じでしょうか？
- GitHub連携機能の認証情報は永続化しない感じですか？

**Comment by yocajii** [comment]
> 解決したい課題、と捉えて、 issueとかproblemとかでもいいかもしれません

例示してくださったこちらの捉え方をヒントにさせていただいて、以下のようにに変更してみました
- Keyを`problem`から`issue`に変更
- `log`を`problem` に変更

> `limit` はタイマーのカウントダウン開始時間ですよね。うっかりタブを閉じてしまったらまた開いたときに `limit` からカウントダウン開始される感じでしょうか？

たしかに、経過時間を保持してないのでこのままだとタブを閉じると消えてしまいますね 😨
`elapsed_time` を追加してみました。

- Key
  `issue`
- Value
  ```
  {
    tobe: "期待する結果",
    asis: "実際の結果",
    problem: "エラーメッセージ、ログ",
    limit: "タイマーの設定時間",
    started_at: "スタートボタンを押した時間 ※Markdownファイルの命名に使う"
    elapsed_time: "タイマーの経過時間"
  }
  ```

> GitHub連携機能の認証情報は永続化しない感じですか？

永続化はしたいと考えています。
一度ライブラリを使わずに自分でaccess_tokenの取得とrefresh_tokenを使った更新処理を書いてみたのですが、LocalStorageかCookieに保存する方法しか思いつかず、セキュリティ対策が十分にできないと考えて[NextAuth.js](https://next-auth.js.org/)を使うことにしました。

NextAuth.jsでは、LocalStoragやCookieにトークンの文字列を直接保存することはなく、Cookieに保存したcsrf-tokenやsession-tokenとReactのSession機能を使って永続化していると理解しています。（が、まだコードやドキュメントを十分に追えておらず、この理解も間違ってるかもしれないです 💦）

▼質問です
SPAで認証情報を保存したい場合にLocalStorageやCookieを使うリスクについて、まだ十分に理解できてはいないのですが、現実的にはLocalStorageやCookieをトークンの保存場所として使うことは開発現場でよくあるのでしょうか。

**Comment by yoshitsugu** [comment]
- issueのほうはURLとあわせて `timer` でもいいかもですね
- > NextAuth.jsでは、LocalStoragやCookieにトークンの文字列を直接保存することはなく、Cookieに保存したcsrf-tokenやsession-tokenとReactのSession機能を使って永続化していると理解しています。（が、まだコードやドキュメントを十分に読めておらず、この理解も間違ってるかもしれないです sweat_drops）
    - なるほどですね。僕もNextAuth.jsは使ったことないのでわかってないのですが、ライブラリがよしなにやってくれそう、ということで理解しました。
- > SPAで認証情報を保存したい場合にLocalStorageやCookieを使うリスクについて、まだ十分に理解できてはいないのですが、現実的にはLocalStorageやCookieをトークンの保存場所として使うことは開発現場でよくあるのでしょうか。
    - ブラウザに何かを保存したい場合、メモリ上に保存するだけだとタブやウィンドウを閉じたタイミングで消えてしまうので、さらに長寿命にしたい場合はlocalStorageかCookieの二択が現実的かなと思います。実際普通はこのどちらかが使われているはずです。
    - ちょっと調べた感じ、Auth0はライブラリでゴニョゴニョすることで永続化しないで実現しているみたいです。すごいですね。
        - [SPA認証トークンはlocalStorageでもCookieでもない、Auth0方式はいいねというお話 - @mizumotokのブログ](https://mizumotok.hatenablog.jp/entry/2021/08/04/114431#%E3%83%96%E3%83%A9%E3%82%A6%E3%82%B6%E3%81%A7%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3%E3%82%92%E4%BF%9D%E5%AD%98%E3%81%A7%E3%81%8D%E3%82%8B%E5%A0%B4%E6%89%80)

**Comment by yocajii** [comment]
お返事が遅くなり申し訳ありません 🙏

> ブラウザに何かを保存したい場合、メモリ上に保存するだけだとタブやウィンドウを閉じたタイミングで消えてしまうので、さらに長寿命にしたい場合はlocalStorageかCookieの二択が現実的かなと思います。実際普通はこのどちらかが使われているはずです。

ありがとうございます、localStorageかCookieが現実的な選択肢になるんですね 👀📝 
NextAuth.jsを入れてはみたのですが、OAuthの処理は理解しておきたいと考えていて、localStorageかCookieを使うのであれば実装イメージが湧くので、自分で実装することも検討してみます。

> issueのほうはURLとあわせて `timer` でもいいかもですね

確かに！と思って取り入れようと考えてみたのですが、自分の中で

timer(ページ全体) = issue + trials

という捉え方をしていることが分かって、ひとまずissueのままにしてみようと思いました。
以下、ここまでの修正を反映したものになります。

---
- Key
  `issue`
- Value
  ```
  {
    tobe: "期待する結果",
    asis: "実際の結果",
    problem: "エラーメッセージ、ログ",
    limit: "タイマーの設定時間",
    started_at: "スタートボタンを押した時間 ※Markdownファイルの命名に使う"
    elapsed_time: "タイマーの経過時間"
  }
  ```

- Key
  `trials`
- Value
  ```
  {
    [
      id: "連番",
      guess: "考えたこと・調べたこと",
      operation: "やったこと",
      result: "やったことの結果"
    ]
  }
  ```

**Comment by yoshitsugu** [comment]
OKです :heavy_check_mark:

**Comment by yocajii** [comment]
リソース・DB設計のプラクティスが修了となったためクローズ。
